repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        # Use the same Python you use locally so results match
        language_version: python3.13
        additional_dependencies:
          - "requests>=2.32.0"
          - "paramiko[nacl]>=3.4.0"
          - "cryptography>=42.0.0"
        args:
          - "--rcfile=.pylintrc"
